/** Hardpoint order: slot 1 Space, slot 2 LMB, slot 3 RMB. */
export const HUD_WEAPON_BINDINGS = ["Space", "LMB", "RMB"] as const;

/** One equipped weapon hardpoint, already matched to its fire button. */
export interface WeaponHudRow {
  binding: string;
  family: string;
  /** null = no magazine (energy). A number is the module's ammo cap. */
  ammoMax: number | null;
  /** Rounds left. Ignored when the weapon has no magazine. */
  ammo: number;
  held: boolean;
  /** Seconds until the next shot is allowed. 0 when the slot is ready. */
  cooldown: number;
}

const HUD_TEXT = "rgba(200, 220, 255, 0.88)";
const HUD_READY = "rgba(255, 214, 72, 0.96)";
const HUD_BLOCKED = "rgba(255, 86, 74, 0.96)";

/**
 * Energy weapons carry no magazine. Kinetics always do.
 * A future family that is not gun, cannon, or missile counts too,
 * so a 0 round count is never shown or treated as empty.
 */
export function weaponRowIsEnergy(row: WeaponHudRow): boolean {
  if (row.ammoMax === null) return true;
  return (
    row.family !== "gun" &&
    row.family !== "cannon" &&
    row.family !== "missile"
  );
}

export function weaponRowLabel(row: WeaponHudRow): string {
  if (weaponRowIsEnergy(row)) return row.binding;
  const rounds = Number.isFinite(row.ammo) ? Math.max(0, Math.floor(row.ammo)) : 0;
  return `${row.binding} ${rounds}`;
}

/**
 * Yellow while the fire button is held and the weapon can shoot.
 * Red while a real cooldown or an empty magazine blocks the next shot.
 * Guns cycle every 0.05s — a held gun with rounds left stays yellow
 * through that pellet gap. Cannon, missile, and energy restart
 * cooldowns stay red until the next shot is allowed.
 * A full heat sink (capacity > 0) blocks an energy weapon from starting.
 */
export function weaponRowTone(
  row: WeaponHudRow,
  heat: number,
  heatSinkCapacity: number,
): "normal" | "ready" | "blocked" {
  const energy = weaponRowIsEnergy(row);
  const depleted = !energy && !(row.ammo > 0);
  if (depleted) return "blocked";

  if (energy && heatSinkCapacity > 0 && heat >= heatSinkCapacity) {
    return "blocked";
  }

  const gunHeldWithAmmo = row.family === "gun" && row.held && !depleted;
  if (row.cooldown > 0 && !gunHeldWithAmmo) return "blocked";

  if (row.held) return "ready";
  return "normal";
}

function toneColor(tone: "normal" | "ready" | "blocked"): string {
  if (tone === "ready") return HUD_READY;
  if (tone === "blocked") return HUD_BLOCKED;
  return HUD_TEXT;
}

export class Hud {
  draw(
    ctx: CanvasRenderingContext2D,
    info: {
      health: number;
      maxHealth: number;
      plating: number;
      maxPlating: number;
      shield: number;
      maxShield: number;
      /** Seconds left before a broken shield starts recharging. */
      shieldBreakRemaining?: number;
      fuel: number;
      maxFuel: number;
      cargoUsed: number;
      cargoCapacity: number;
      passengerUsed?: number;
      passengerCapacity?: number;
      credits: number;
      /** Equipped weapons only, hardpoint order. Empty slots are omitted. */
      weapons?: WeaponHudRow[];
      /** Current drive heat. Gauge fill is heat / heatSinkCapacity. */
      heat?: number;
      /** 0 hides the gauge. No heat is generated by the HUD. */
      heatSinkCapacity?: number;
      poiName: string;
      locationName: string;
      poiType: string;
      starClass?: string;
      menuOpen: boolean;
      inBelt?: boolean;
      canProspect?: boolean;
      inDerelict?: boolean;
      hasScoop?: boolean;
      derelictScoopHint?: boolean;
      /** Pending explore mission at this POI — show hold-F survey hint. */
      surveyScanHint?: boolean;
      hasSurveyScanner?: boolean;
    },
  ): void {
    if (info.menuOpen) return;

    const pad = 16;
    ctx.save();
    ctx.font = "13px ui-monospace, SFMono-Regular, Menlo, Consolas, monospace";
    ctx.fillStyle = HUD_TEXT;
    ctx.textBaseline = "top";

    const title =
      info.poiType === "starSystem" && info.starClass
        ? `${info.poiName}  (${info.starClass})`
        : `${formatType(info.poiType)}  ${info.poiName}`;

    // Skip location when it repeats the system/star title (e.g. at the host star).
    const showLocation =
      info.locationName.length > 0 &&
      info.locationName !== info.poiName &&
      info.locationName !== `${info.poiName} (${info.starClass})`;

    const lines = [
      title,
      ...(showLocation ? [info.locationName] : []),
      "",
      `HP ${Math.ceil(info.health)}/${info.maxHealth}`,
      ...(info.maxPlating > 0
        ? [`PL ${Math.ceil(info.plating)}/${info.maxPlating}`]
        : []),
      ...(info.maxShield > 0
        ? [
            `SH ${Math.ceil(info.shield)}/${info.maxShield}${
              (info.shieldBreakRemaining ?? 0) > 0
                ? ` (down ${(info.shieldBreakRemaining ?? 0).toFixed(1)}s)`
                : ""
            }`,
          ]
        : []),
      ...(info.maxFuel > 0
        ? [`FU ${Math.floor(info.fuel)}/${info.maxFuel}`]
        : []),
      ...(info.cargoCapacity > 0
        ? [`CU ${info.cargoUsed}/${info.cargoCapacity}`]
        : []),
      ...((info.passengerCapacity ?? 0) > 0
        ? [
            `BR ${info.passengerUsed ?? 0}/${info.passengerCapacity ?? 0}`,
          ]
        : []),
      `CR ${info.credits}`,
    ];

    let y = pad;
    for (const line of lines) {
      ctx.fillText(line, pad, y);
      y += 17;
    }

    if (info.inBelt && info.canProspect) {
      y += 8;
      ctx.fillStyle = "rgba(200, 210, 170, 0.8)";
      ctx.fillText("Belt · hold F to scoop ore", pad, y);
    } else if (info.inDerelict && info.derelictScoopHint && info.hasScoop) {
      // Same HUD band as belt prospecting (not floating on debris).
      y += 8;
      ctx.fillStyle = "rgba(220, 200, 150, 0.85)";
      ctx.fillText("Derelict · hold F to scoop cargo", pad, y);
    } else if (info.surveyScanHint && info.hasSurveyScanner) {
      y += 8;
      ctx.fillStyle = "rgba(170, 210, 220, 0.85)";
      ctx.fillText("Survey · hold F to scan", pad, y);
    } else if (info.surveyScanHint && !info.hasSurveyScanner) {
      y += 8;
      ctx.fillStyle = "rgba(200, 160, 140, 0.85)";
      ctx.fillText("Survey · Requires Survey Scanner", pad, y);
    }

    ctx.fillStyle = "rgba(150, 170, 200, 0.55)";
    ctx.fillText("G  Galaxy", pad, window.innerHeight - 58);
    ctx.fillText("M  System", pad, window.innerHeight - 40);
    ctx.fillText("L  Ship", pad, window.innerHeight - 22);

    // Bottom-right. The ship and missile reticle sit at screen center,
    // hull/shield text is top-left, and G/M/L occupy the bottom-left.
    // Comms is a top-right panel, so this corner is the open edge.
    this.drawWeaponCluster(
      ctx,
      info.weapons ?? [],
      info.heat ?? 0,
      info.heatSinkCapacity ?? 0,
    );

    ctx.restore();
  }

  private drawWeaponCluster(
    ctx: CanvasRenderingContext2D,
    weapons: WeaponHudRow[],
    heat: number,
    heatSinkCapacity: number,
  ): void {
    const showBar = heatSinkCapacity > 0;
    if (weapons.length === 0 && !showBar) return;

    const margin = 16;
    const lineH = 17;
    const barW = 112;
    const barH = 6;
    const barGap = 8;
    const right = window.innerWidth - margin;
    const clusterH =
      weapons.length * lineH + (showBar ? (weapons.length > 0 ? barGap : 0) + barH : 0);
    let y = window.innerHeight - margin - clusterH;

    ctx.save();
    ctx.font = "13px ui-monospace, SFMono-Regular, Menlo, Consolas, monospace";
    ctx.textAlign = "right";
    ctx.textBaseline = "top";
    for (const row of weapons) {
      ctx.fillStyle = toneColor(weaponRowTone(row, heat, heatSinkCapacity));
      ctx.fillText(weaponRowLabel(row), right, y);
      y += lineH;
    }

    if (showBar) {
      if (weapons.length > 0) y += barGap;
      const frac = Math.max(0, Math.min(1, heat / heatSinkCapacity));
      const x = right - barW;
      ctx.fillStyle = "rgba(18, 22, 32, 0.85)";
      ctx.fillRect(x, y, barW, barH);
      ctx.strokeStyle = "rgba(150, 170, 200, 0.45)";
      ctx.lineWidth = 1;
      ctx.strokeRect(x + 0.5, y + 0.5, barW - 1, barH - 1);
      ctx.fillStyle = "rgba(255, 148, 48, 0.95)";
      ctx.fillRect(x, y, barW * frac, barH);
    }
    ctx.restore();
  }
}

function formatType(t: string): string {
  switch (t) {
    case "starSystem":
      return "System";
    case "blackHole":
      return "Black hole";
    case "derelict":
      return "Derelict";
    case "neutronStar":
      return "Neutron star";
    case "brownDwarf":
      return "Brown dwarf";
    case "roguePlanet":
      return "Rogue planet";
    case "nebula":
      return "Nebula";
    default:
      return "POI";
  }
}
