import { tierLabel, type ModuleTier } from "../ship/equipment";

/** Display order: left click, Space, right click. */
export const WEAPON_HUD_INPUTS = ["L-MOUSE", "SPACE", "R-MOUSE"] as const;

/**
 * One equipped hardpoint.
 * Columns are left click, Space, right click. Null leaves that column blank.
 */
export interface WeaponHudRow {
  /** L-MOUSE, SPACE, or R-MOUSE. */
  input: string;
  /** Complete module name with its mark, e.g. Gun Mk II. */
  name: string;
  family: string;
  /** null = no magazine (energy). A number is the module's ammo cap. */
  ammoMax: number | null;
  /** Rounds left. Ignored when the weapon has no magazine. */
  ammo: number;
  held: boolean;
  /** Seconds until the next shot is allowed. 0 when the slot is ready. */
  cooldown: number;
}

const HUD_TEXT = "rgba(200, 220, 255, 0.88)";
const HUD_READY = "rgba(255, 214, 72, 0.96)";
const HUD_BLOCKED = "rgba(255, 86, 74, 0.96)";

/**
 * Energy weapons carry no magazine. Kinetics always do.
 * A future family that is not gun, cannon, or missile counts too,
 * so a 0 round count is never shown or treated as empty.
 */
export function weaponRowIsEnergy(row: WeaponHudRow): boolean {
  if (row.ammoMax === null) return true;
  return (
    row.family !== "gun" &&
    row.family !== "cannon" &&
    row.family !== "missile"
  );
}

/** Module name plus its mark, e.g. `Gun Mk II` or `Energy Pulse Mk I`. */
export function weaponCompleteName(name: string, tier: ModuleTier): string {
  return `${name} ${tierLabel(tier)}`;
}

/** Current ammo, or null when the weapon has no magazine. */
export function weaponAmmoLabel(row: WeaponHudRow): string | null {
  if (weaponRowIsEnergy(row)) return null;
  const rounds = Number.isFinite(row.ammo) ? Math.max(0, Math.floor(row.ammo)) : 0;
  return String(rounds);
}

/**
 * Yellow while the fire button is held and the weapon can shoot.
 * Red while a real cooldown or an empty magazine blocks the next shot.
 * Guns cycle every 0.05s — a held gun with rounds left stays yellow
 * through that pellet gap. Cannon, missile, and energy restart
 * cooldowns stay red until the next shot is allowed.
 * A full heat sink (capacity > 0) blocks an energy weapon from starting.
 */
export function weaponRowTone(
  row: WeaponHudRow,
  heat: number,
  heatSinkCapacity: number,
): "normal" | "ready" | "blocked" {
  const energy = weaponRowIsEnergy(row);
  const depleted = !energy && !(row.ammo > 0);
  if (depleted) return "blocked";

  if (energy && heatSinkCapacity > 0 && heat >= heatSinkCapacity) {
    return "blocked";
  }

  const gunHeldWithAmmo = row.family === "gun" && row.held && !depleted;
  if (row.cooldown > 0 && !gunHeldWithAmmo) return "blocked";

  if (row.held) return "ready";
  return "normal";
}

function toneColor(tone: "normal" | "ready" | "blocked"): string {
  if (tone === "ready") return HUD_READY;
  if (tone === "blocked") return HUD_BLOCKED;
  return HUD_TEXT;
}

export class Hud {
  draw(
    ctx: CanvasRenderingContext2D,
    info: {
      health: number;
      maxHealth: number;
      plating: number;
      maxPlating: number;
      shield: number;
      maxShield: number;
      /** Seconds left before a broken shield starts recharging. */
      shieldBreakRemaining?: number;
      fuel: number;
      maxFuel: number;
      cargoUsed: number;
      cargoCapacity: number;
      passengerUsed?: number;
      passengerCapacity?: number;
      credits: number;
      /**
       * Three columns: left click, Space, right click.
       * Null leaves that column blank.
       */
      weapons?: readonly (WeaponHudRow | null)[];
      /** Current drive heat. Gauge fill is heat / heatSinkCapacity. */
      heat?: number;
      /** 0 hides the gauge. No heat is generated by the HUD. */
      heatSinkCapacity?: number;
      poiName: string;
      locationName: string;
      poiType: string;
      starClass?: string;
      menuOpen: boolean;
      inBelt?: boolean;
      canProspect?: boolean;
      inDerelict?: boolean;
      hasScoop?: boolean;
      derelictScoopHint?: boolean;
      /** Pending explore mission at this POI — show hold-F survey hint. */
      surveyScanHint?: boolean;
      hasSurveyScanner?: boolean;
    },
  ): void {
    if (info.menuOpen) return;

    const pad = 16;
    ctx.save();
    ctx.font = "13px ui-monospace, SFMono-Regular, Menlo, Consolas, monospace";
    ctx.fillStyle = HUD_TEXT;
    ctx.textBaseline = "top";

    const title =
      info.poiType === "starSystem" && info.starClass
        ? `${info.poiName}  (${info.starClass})`
        : `${formatType(info.poiType)}  ${info.poiName}`;

    // Skip location when it repeats the system/star title (e.g. at the host star).
    const showLocation =
      info.locationName.length > 0 &&
      info.locationName !== info.poiName &&
      info.locationName !== `${info.poiName} (${info.starClass})`;

    const lines = [
      title,
      ...(showLocation ? [info.locationName] : []),
      "",
      `HP ${Math.ceil(info.health)}/${info.maxHealth}`,
      ...(info.maxPlating > 0
        ? [`PL ${Math.ceil(info.plating)}/${info.maxPlating}`]
        : []),
      ...(info.maxShield > 0
        ? [
            `SH ${Math.ceil(info.shield)}/${info.maxShield}${
              (info.shieldBreakRemaining ?? 0) > 0
                ? ` (down ${(info.shieldBreakRemaining ?? 0).toFixed(1)}s)`
                : ""
            }`,
          ]
        : []),
      ...(info.maxFuel > 0
        ? [`FU ${Math.floor(info.fuel)}/${info.maxFuel}`]
        : []),
      ...(info.cargoCapacity > 0
        ? [`CU ${info.cargoUsed}/${info.cargoCapacity}`]
        : []),
      ...((info.passengerCapacity ?? 0) > 0
        ? [
            `BR ${info.passengerUsed ?? 0}/${info.passengerCapacity ?? 0}`,
          ]
        : []),
      `CR ${info.credits}`,
    ];

    let y = pad;
    for (const line of lines) {
      ctx.fillText(line, pad, y);
      y += 17;
    }

    if (info.inBelt && info.canProspect) {
      y += 8;
      ctx.fillStyle = "rgba(200, 210, 170, 0.8)";
      ctx.fillText("Belt · hold F to scoop ore", pad, y);
    } else if (info.inDerelict && info.derelictScoopHint && info.hasScoop) {
      // Same HUD band as belt prospecting (not floating on debris).
      y += 8;
      ctx.fillStyle = "rgba(220, 200, 150, 0.85)";
      ctx.fillText("Derelict · hold F to scoop cargo", pad, y);
    } else if (info.surveyScanHint && info.hasSurveyScanner) {
      y += 8;
      ctx.fillStyle = "rgba(170, 210, 220, 0.85)";
      ctx.fillText("Survey · hold F to scan", pad, y);
    } else if (info.surveyScanHint && !info.hasSurveyScanner) {
      y += 8;
      ctx.fillStyle = "rgba(200, 160, 140, 0.85)";
      ctx.fillText("Survey · Requires Survey Scanner", pad, y);
    }

    ctx.fillStyle = "rgba(150, 170, 200, 0.55)";
    ctx.fillText("G  Galaxy", pad, window.innerHeight - 58);
    ctx.fillText("M  System", pad, window.innerHeight - 40);
    ctx.fillText("L  Ship", pad, window.innerHeight - 22);

    // Top center, clear of the top-left hull readout and the bottom-edge prompts.
    this.drawWeaponCluster(
      ctx,
      info.weapons ?? [],
      info.heat ?? 0,
      info.heatSinkCapacity ?? 0,
    );

    ctx.restore();
  }

  private drawWeaponCluster(
    ctx: CanvasRenderingContext2D,
    weapons: readonly (WeaponHudRow | null)[],
    heat: number,
    heatSinkCapacity: number,
  ): void {
    const columns: (WeaponHudRow | null)[] = [
      weapons[0] ?? null,
      weapons[1] ?? null,
      weapons[2] ?? null,
    ];
    const showBar = heatSinkCapacity > 0;
    if (!columns.some((row) => row !== null) && !showBar) return;

    const gap = 14;
    const padX = 8;
    const padY = 6;
    const lineH = 16;
    const top = 14;

    ctx.save();
    ctx.font = "13px ui-monospace, SFMono-Regular, Menlo, Consolas, monospace";
    ctx.textAlign = "center";
    ctx.textBaseline = "top";

    // Wide enough for the longest marked weapon name, so the label is not clipped.
    let textW = ctx.measureText("Energy Pulse Mk III").width;
    for (const row of columns) {
      if (!row) continue;
      textW = Math.max(
        textW,
        ctx.measureText(row.input).width,
        ctx.measureText(row.name).width,
      );
    }
    const colW = Math.ceil(textW) + padX * 2;
    const totalW = colW * 3 + gap * 2;
    const originX = (window.innerWidth - totalW) / 2;
    const keyY = top + padY;
    const nameY = keyY + lineH;
    const ammoY = nameY + lineH;

    for (let i = 0; i < columns.length; i += 1) {
      const row = columns[i];
      if (!row) continue;
      const x = originX + i * (colW + gap);
      const energy = weaponRowIsEnergy(row);
      const boxH = padY * 2 + lineH * (energy ? 2 : 3);
      ctx.fillStyle = "rgba(8, 12, 20, 0.55)";
      ctx.fillRect(x, top, colW, boxH);
      ctx.strokeStyle = "rgba(150, 170, 200, 0.35)";
      ctx.lineWidth = 1;
      ctx.strokeRect(x + 0.5, top + 0.5, colW - 1, boxH - 1);

      ctx.fillStyle = toneColor(weaponRowTone(row, heat, heatSinkCapacity));
      const cx = x + colW / 2;
      ctx.fillText(row.input, cx, keyY);
      ctx.fillText(row.name, cx, nameY);
      const ammo = weaponAmmoLabel(row);
      if (ammo !== null) ctx.fillText(ammo, cx, ammoY);
    }

    if (showBar) {
      const barW = 120;
      const barH = 6;
      const barX = (window.innerWidth - barW) / 2;
      const ammoBoxH = padY * 2 + lineH * 3;
      const barY = top + ammoBoxH + 6;
      const frac = Math.max(0, Math.min(1, heat / heatSinkCapacity));
      ctx.fillStyle = "rgba(18, 22, 32, 0.85)";
      ctx.fillRect(barX, barY, barW, barH);
      ctx.strokeStyle = "rgba(150, 170, 200, 0.45)";
      ctx.lineWidth = 1;
      ctx.strokeRect(barX + 0.5, barY + 0.5, barW - 1, barH - 1);
      ctx.fillStyle = "rgba(255, 148, 48, 0.95)";
      ctx.fillRect(barX, barY, barW * frac, barH);
    }
    ctx.restore();
  }
}

function formatType(t: string): string {
  switch (t) {
    case "starSystem":
      return "System";
    case "blackHole":
      return "Black hole";
    case "derelict":
      return "Derelict";
    case "neutronStar":
      return "Neutron star";
    case "brownDwarf":
      return "Brown dwarf";
    case "roguePlanet":
      return "Rogue planet";
    case "nebula":
      return "Nebula";
    default:
      return "POI";
  }
}
